version: '3.8'

services:
  admin-panel:
    build: .
    container_name: masjid-admin-panel
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
    # Optional: add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s