// Environment variables configuration
// This file is generated at build time and contains environment variables
// Do not edit manually - it will be overwritten

window.ENV = {
  FIREBASE_API_KEY: "PLACEHOLDER_FIREBASE_API_KEY",
  FIREBASE_AUTH_DOMAIN: "PLACEHOLDER_FIREBASE_AUTH_DOMAIN", 
  FIREBASE_PROJECT_ID: "PLACEHOLDER_FIREBASE_PROJECT_ID",
  FIREBASE_STORAGE_BUCKET: "PLACEHOLDER_FIREBASE_STORAGE_BUCKET",
  FIREBASE_MESSAGING_SENDER_ID: "PLACEHOLDER_FIREBASE_MESSAGING_SENDER_ID",
  FIREBASE_APP_ID: "PLACEHOLDER_FIREBASE_APP_ID"
};